### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive-operator#6]
Has it been replaced by https://github.com/openshift/hive/tree/master/pkg/operator ?

FYI @dgoodwin

**Comment by dgoodwin** [comment]
Yes, was never used really.

**Comment by dgoodwin** [comment]
I just heard some details on why you might be looking for this. This repo was written by an intern at a time where we thought of the operator as being a separate layer above hive. Over time that definition of operator changed and we were encouraged to have the component itself *be* an operator.

This was abandoned and today we have the hive-operator pod, which is overseeing the core components of hive.

Additionally, and more confusingly, we have a start on what would be required to generate an operator on OperatorHub or the marketplace here: https://github.com/openshift/hive/blob/master/hack/generate-operator-bundle.py We use this to genereate OLM bundles that we use to roll out updates to hive in stage and prod today. This script would form a good basis for generating the artifacts required to get Hive properly listed on the marketplace.

**Comment by dgoodwin** [comment]
The hive-operator pod is probably confusingly named, we consider Hive itself an operator.

**Comment by gyliu513** [comment]
Good to know and thanks for the detailed explanation @dgoodwin 😄
